- alias: Turn on Office Stairs light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.office_stairs_motion_sensor_motion
    to: 'on'
  action:
    service: light.turn_on
    entity_id: group.office_stairs

- alias: Turn off Office Stairs 10 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.office_stairs_motion_sensor_motion
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: group.office_stairs
    
- alias: Turn on Master Bedroom Cupboard lights when door is open
  trigger:
    platform: state
    entity_id: binary_sensor.cupboard_right_contact
    to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.extended_color_light_2_2
        brightness: 50
    - service: light.turn_on
      data:
        entity_id: light.extended_color_light_2_2
        brightness: 50
    
- alias: Turn off Master Bedroom Cupboard lights when door is closed
  trigger:
    platform: state
    entity_id: binary_sensor.cupboard_right_contact
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.extended_color_light_2_2
        
- alias: Turn TV lights to orange when watching Hockey
  trigger:
    platform: state
    entity_id: media_player.living_room_chromecast
    to: 'playing'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ 'Flyers' in state_attr('media_player.living_room_chromecast', 'media_title') }}"
      - condition: template
        value_template: "{{ is_state_attr('media_player.living_room_chromecast', 'app_name', 'Chrome Mirroring') }}"
  action:
    - service: light.turn_on
      data:
        entity_id: light.living_room
        rgb_color: [255,137,32]
    - service: light.turn_on
      data:
        entity_id: light.living_room
        rgb_color: [255,137,32]
        
- alias: Turn TV lights to white if Chromecast is selected and nothing is playing
  trigger:
    platform: state
    entity_id: media_player.living_room_chromecast
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.living_room_tv', 'source', 'HDMI4')}}"
  action:
    - service: light.turn_on
      data: 
        entity_id: light.living_room
        rgb_color: [207,191,255]
    - service: light.turn_on
      data: 
        entity_id: light.living_room
        rgb_color: [207,191,255]