
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
  
scene:
  platform: hunterdouglas_powerview
  address: !secret powerview_ip

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml

media_player:
  - platform: webostv
    host: !secret living_room_tv_ip
    name: Living Room TV
    filename: webostv.conf
    timeout: 5
    
notify:
  - platform: webostv
    host: !secret living_room_tv_ip
    name: living_room_tv
    filename: webostv.conf